# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'testcocoapod' do
pod 'AFNetworking', '~> 2.5'
pod 'Google/Analytics'
end

target 'testcocoapodTests' do

end

target 'testcocoapodUITests' do

end

